<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Whiley</string>
  <key>scopeName</key>
  <string>source.whiley</string>
  <key>fileTypes</key>
  <array>
    <string>whiley</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comment</string>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.import.whiley</string>
      <key>begin</key>
      <string>\b(import)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.import.whiley</string>
        </dict>
      </dict>
      <key>end</key>
      <string>($|;)</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>name</key>
          <string>keyword.from.whiley</string>
          <key>match</key>
          <string>\b(from)\b</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#module_name</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.define.whiley</string>
      <key>match</key>
      <string>\b(define)\s+(\w+)\s+(as)</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.define.whiley</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>constant.define.whiley</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>keyword.as.whiley</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>meta.method.whiley</string>
      <key>begin</key>
      <string>\b(\w+)\s+(?:([\w.]+)?(?:::\s*))?(\w+)\(</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>storage.type.return.whiley</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>constant.type.receiver.whiley</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>entity.method.whiley</string>
        </dict>
      </dict>
      <key>end</key>
      <string>:</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>([\w.]+)\s+\w+</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.parameter.whiley</string>
            </dict>
          </dict>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>entity.record.key.whiley</string>
      <key>match</key>
      <string>\w+:</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.this.whiley</string>
      <key>match</key>
      <string>\b(this)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.whiley</string>
      <key>match</key>
      <string>\b(import|from|define|as|ref|spawn|return)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>storage.type.whiley</string>
      <key>match</key>
      <string>\b(void|int|real|string)\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>keyword.operator.whiley</string>
      <key>match</key>
      <string>[.|!%$?&amp;\*~+\-=&lt;/&gt;\\]+</string>
    </dict>
    <dict>
      <key>name</key>
      <string>string.quoted.double.whiley</string>
      <key>begin</key>
      <string>"</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.begin.whiley</string>
        </dict>
      </dict>
      <key>end</key>
      <string>"</string>
      <key>endCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.string.end.whiley</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
          <key>name</key>
          <string>constant.character.escape.gwhiley</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.numeric.whiley</string>
      <key>match</key>
      <string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.boolean.true.whiley</string>
      <key>match</key>
      <string>\btrue\b</string>
    </dict>
    <dict>
      <key>name</key>
      <string>constant.language.boolean.false.whiley</string>
      <key>match</key>
      <string>\bfalse\b</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>comment</key>
    <dict>
      <key>match</key>
      <string>//.*$</string>
      <key>name</key>
      <string>comment.line.whiley</string>
    </dict>
    <key>module_name</key>
    <dict>
      <key>match</key>
      <string>[\w*.]</string>
      <key>name</key>
      <string>support.other.module.whiley</string>
    </dict>
  </dict>
  <key>uuid</key>
  <string>ca03e751-04ef-4330-9a6b-9b99aae1c41a</string>
</dict>
</plist>
